// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkIEV_x2ktollGx40kJbsOSfXAqaw7OR0',
    appId: '1:362050500432:web:b319c382bcf905730a5e55',
    messagingSenderId: '362050500432',
    projectId: 'petch-563c4',
    authDomain: 'petch-563c4.firebaseapp.com',
    storageBucket: 'petch-563c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYC-sYICdcp1J2xB0YouO-mLuWNI8bS_4',
    appId: '1:362050500432:android:fa067e19367c1c740a5e55',
    messagingSenderId: '362050500432',
    projectId: 'petch-563c4',
    storageBucket: 'petch-563c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2NFZNu4KStobUNWAkpZH7gCQ5kZmtfM',
    appId: '1:362050500432:ios:166a75d5e9531b470a5e55',
    messagingSenderId: '362050500432',
    projectId: 'petch-563c4',
    storageBucket: 'petch-563c4.appspot.com',
    iosClientId: '362050500432-dvkopdf28ndh56qrscrkscmfspa6c27r.apps.googleusercontent.com',
    iosBundleId: 'com.pmaster.petch',
  );
}
